return {
  -- {
  --   'sphamba/smear-cursor.nvim',
  --   enable = false,
  --   opts = {
  --     smear_between_buffers = false,
  --     legacy_computing_symbols_support = true,
  --     transparent_bg_fallback_color = '#303030',
  --     config = function()
  --       local smear = require 'smear_cursor'
  --       smear:setup {
  --         stiffness = 0.8, -- 0.6      [0, 1]
  --         trailing_stiffness = 0.6, -- 0.45     [0, 1]
  --         stiffness_insert_mode = 0.7, -- 0.5      [0, 1]
  --         trailing_stiffness_insert_mode = 0.7, -- 0.5      [0, 1]
  --         damping = 0.95, -- 0.85     [0, 1]
  --         damping_insert_mode = 0.95, -- 0.9      [0, 1]
  --         distance_stop_animating = 0.5, -- 0.1      > 0
  --       }
  --     end,
  --   },
  -- },
}
